### ISSUE TITLE
Is it possible to run first-order-model on mobile device?

### ISSUE THREAD

**Issue by la0216** [AliaksandrSiarohin/first-order-model#382]
I'm not sure whether I can run the first-order-model on mobile device, does anyone have suggestions on this?
For example, compress the model, quantize the model or retrain the model, etc. 
Any suggesitons will be appreciated.

**Comment by AliaksandrSiarohin** [comment]
It is possible, because some people make an mobile app out of this. But I'm not an expert in runtime optimization, so could not tell. Everything that you suggest could be tried.

**Comment by la0216** [comment]
Thank you so much for your feedback. Do you mean avatarify app?

**Comment by AliaksandrSiarohin** [comment]
For example, yes avatarify.

**Comment by Noahz110** [comment]
You cant run this on a mobile device for the time being. Instead you can build a mobile app to call api to your server which do the rest.

**Comment by sendy50** [comment]
ok but how hosting this code i complete run this repository but i don't know how to host on server Any suggesitons will be appreciated.

**Comment by sendy50** [comment]
> 
> 
> You cant run this on a mobile device for the time being. Instead you can build a mobile app to call api to your server which do the rest.

**Comment by sendy50** [comment]
ok but how i hosting this code i complete run this repository in windows but i don't know how to host on server Any suggesitons will be appreciated.

**Comment by HashedViking** [comment]
@AliaksandrSiarohin Are there some settings/arguments in generator, for example, that could be tweaked (even giving up the result quality) to boost the performance?

**Comment by AliaksandrSiarohin** [comment]
I never tried this, I guess tricks with replacing standard blocks with mobile net blocks should not hurt the performance much.

**Comment by sendy50** [comment]
Okk but any flow for this ? I haven't any idea

**Comment by HashedViking** [comment]
> I never tried this, I guess tricks with replacing standard blocks with mobile net blocks should not hurt the performance much.

@AliaksandrSiarohin 
Thank you for a rapid reply.
Could you, please, show some code snippets of how to use/replace those blocks? 
Is there anything else can be replaced/tweaked to reduce the computation complexity? 
May be some parameters like these:
```
  generator_params:
    block_expansion: 64
    max_features: 512
    num_down_blocks: 2
    num_bottleneck_blocks: 6
    estimate_occlusion_map: True
    dense_motion_params:
      block_expansion: 64
      max_features: 1024
      num_blocks: 5
      scale_factor: 0.25
```
